"""CKLB (DISA STIG Viewer 3 checklist) export — ASD STIG V6R4 (`report --format cklb`).

Contract verified 2026-08-24 BEFORE coding, per project convention:
- Document shape mirrors the DoD reference producer — STIG Manager's
  `cklbFromAssetStigs` (NUWCDIVNPT/stig-manager, api/source/service/AssetService.js):
  top-level {title, id, active, mode, has_path, target_data{...}, stigs[]},
  stigs[] = {stig_name, display_name, stig_id, version, release_info, uuid,
  reference_identifier, size, rules[]}, rules[] carrying the full embedded STIG
  rule metadata plus {status, finding_details, comments, ccis}.
- Rule metadata (ids, titles, discussion, check/fix text, CCIs) is reproduced
  VERBATIM from the official `U_ASD_V6R4` XCCDF (vendored at
  `data/asd-stig-v6r4-rules.json` with download URL + zip sha256; DISA STIGs
  are publicly released US Government works). `rule_version` carries the
  APSC-DV id — the stable mapping key (plan R4: map on APSC-DV, never CCI).

Mapping (every id verified in the official XCCDF): exact-CWE overrides first,
then cwe_family, else the code-review catch-all APSC-DV-003170. Statuses are
conservative by design: a mapped rule with >=1 exportable finding is "open";
every other included rule is "not_reviewed" — an automated scan can never
assert "not_a_finding", and D7 withholding applies (suppressed / demoted
findings never reach finding_details; they are counted in meta instead).

This is a PARTIAL checklist: only the SAST-informable subset of the 286 ASD
rules is included. Spec-shaped after the reference producer, not yet imported
into a live STIG Viewer (same honest status the CI templates carry).
"""

from __future__ import annotations

import json
import uuid
from pathlib import Path

from ..model import Finding, canonical_cwe
from . import open_unresolved

_NS = uuid.UUID("6ba7b811-9dad-11d1-80b4-00c04fd430c8")   # uuid5 namespace (URL ns)
RULES_PATH = Path(__file__).parent.parent / "data" / "asd-stig-v6r4-rules.json"

# Exact-CWE overrides (checked before the family table).
CWE_TO_RULE = {
    "CWE-89": "APSC-DV-002540", "CWE-564": "APSC-DV-002540", "CWE-943": "APSC-DV-002540",
    "CWE-78": "APSC-DV-002510", "CWE-77": "APSC-DV-002510",
    "CWE-91": "APSC-DV-002550", "CWE-643": "APSC-DV-002550",
    "CWE-22": "APSC-DV-002520",
    "CWE-328": "APSC-DV-002030",
    "CWE-330": "APSC-DV-002290", "CWE-338": "APSC-DV-002290",
    "CWE-532": "APSC-DV-000650",
    "CWE-117": "APSC-DV-001290",
}
FAMILY_TO_RULE = {
    "injection": "APSC-DV-002560",
    "xss": "APSC-DV-002490",
    "path_traversal": "APSC-DV-002520",
    "crypto": "APSC-DV-002040",
    "secrets": "APSC-DV-003110",
    "supply_chain": "APSC-DV-002630",
    "authz": "APSC-DV-000460",
    "authn": "APSC-DV-001540",
    "memory": "APSC-DV-002590",
    "dos": "APSC-DV-002400",
    "deserialization": "APSC-DV-002560",
    "ssrf": "APSC-DV-002560",
}
CATCH_ALL = "APSC-DV-003170"     # code review performed (R4-sanctioned catch-all)


def _uuid(*parts: str) -> str:
    return str(uuid.uuid5(_NS, "security-council/cklb\x00" + "\x00".join(parts)))


def rule_for(f: Finding) -> str:
    for cwe in f.taxonomy.cwe:
        if (r := CWE_TO_RULE.get(canonical_cwe(cwe))):
            return r
    return FAMILY_TO_RULE.get(f.taxonomy.cwe_family or "", CATCH_ALL)


def _finding_line(f: Finding) -> str:
    loc = f.locations[0] if f.locations else None
    where = f"{loc.uri}:{loc.start_line}-{loc.end_line}" if loc else "(no location)"
    srcs = ", ".join(sorted({p.source_id for p in f.provenance}))
    cwes = ", ".join(f.taxonomy.cwe) or "CWE-noinfo"
    return (f"[{f.severity.label.upper()}] {f.title}\n"
            f"  at {where}\n"
            f"  {cwes} · reported by {srcs} · finding id {f.id}")


def to_cklb(findings: list[Finding], manifest: dict, *,
            classification: str = "UNCLASSIFIED") -> tuple[dict, dict]:
    """-> (cklb document, meta). meta counts exported / withheld / catch-all so
    a partial checklist can never be mistaken for a full assessment."""
    table = json.loads(RULES_PATH.read_text())
    src, rules_meta = table["source"], table["rules"]
    run_id = str(manifest.get("run_id", "run"))
    tgt = manifest.get("target") or {}
    repo = str(tgt.get("root") or "repository").rstrip("/").rsplit("/", 1)[-1]

    by_rule: dict[str, list[Finding]] = {}
    withheld = 0
    for f in findings:
        if not open_unresolved(f):
            withheld += 1
            continue
        by_rule.setdefault(rule_for(f), []).append(f)

    stig_uuid = _uuid(run_id, "stig")
    gen_note = (f"Generated by security-council run {run_id} (automated SAST evidence "
                "only — manual review of this requirement is still required).")
    rules_out = []
    for ver in sorted(rules_meta):
        meta_r = rules_meta[ver]
        matched = by_rule.get(ver, [])
        status = "open" if matched else "not_reviewed"
        details = "\n\n".join(_finding_line(f) for f in matched)
        comment = gen_note if matched else \
            f"No findings from the automated scan mapped to this requirement. {gen_note}"
        rules_out.append({
            "uuid": _uuid(run_id, "rule", ver),
            "stig_uuid": stig_uuid,
            "target_key": None,
            "stig_ref": None,
            "group_id": meta_r["group_id"],
            "rule_id": meta_r["rule_id"],
            "rule_id_src": meta_r["rule_id_src"],
            "weight": meta_r["weight"],
            "classification": classification,
            "severity": meta_r["severity"],
            "rule_version": ver,
            "group_title": meta_r["group_title"],
            "rule_title": meta_r["rule_title"],
            "fix_text": meta_r["fix_text"],
            "false_positives": "",
            "false_negatives": "",
            "discussion": meta_r["discussion"],
            "check_content": meta_r["check_content"],
            "documentable": "false",
            "mitigations": "",
            "potential_impacts": "",
            "third_party_tools": "",
            "mitigation_control": "",
            "responsibility": "",
            "security_override_guidance": "",
            "ia_controls": "",
            "check_content_ref": {"href": "", "name": "M"},
            "legacy_ids": [],
            "group_tree": [{"id": meta_r["group_id"], "title": meta_r["group_title"],
                            "description": "<GroupDescription></GroupDescription>"}],
            "createdAt": manifest.get("finished_at") or manifest.get("started_at") or "",
            "updatedAt": manifest.get("finished_at") or manifest.get("started_at") or "",
            "STIGUuid": stig_uuid,
            "status": status,
            "overrides": {},
            "comments": comment,
            "finding_details": details,
            "ccis": meta_r["ccis"],
        })

    doc = {
        "title": f"{repo} — security-council {run_id}",
        "id": _uuid(run_id, "checklist"),
        "active": False,
        "mode": 1,
        "has_path": True,
        "target_data": {
            "target_type": "Non-Computing",
            "host_name": repo,
            "ip_address": "",
            "mac_address": "",
            "fqdn": "",
            "comments": (f"security-council run {run_id}"
                         + (f" · git {tgt['git_commit'][:12]}" if tgt.get("git_commit") else "")
                         + " · partial checklist: SAST-informable ASD rules only"),
            "role": "None",
            "is_web_database": False,
            "technology_area": "",
            "web_db_site": "",
            "web_db_instance": "",
        },
        "stigs": [{
            "stig_name": src["stig_name"],
            "display_name": src["stig_name"].replace(
                " Security Technical Implementation Guide", ""),
            "stig_id": src["benchmark_id"],
            "version": src["version"],
            "release_info": src["release_info"],
            "uuid": stig_uuid,
            "reference_identifier": "0000",
            "size": len(rules_out),
            "rules": rules_out,
        }],
    }
    meta = {
        "rules_total": len(rules_out),
        "rules_open": sum(1 for r in rules_out if r["status"] == "open"),
        "findings_exported": sum(len(v) for v in by_rule.values()),
        "withheld_by_disposition": withheld,
        "catch_all_findings": len(by_rule.get(CATCH_ALL, [])),
        "stig": f"{src['benchmark_id']} V{src['version']} ({src['release_info']})",
    }
    return doc, meta
